package model.dtos;
// Generated 31-May-2016 22:35:14 by Hibernate Tools 4.3.1


import model.pojos.*;
import java.util.Date;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import org.codehaus.jettison.json.JSONObject;

/**
 * FeedsDto generated by hbm2java
 */
@XmlRootElement
public class FeedsDto  implements java.io.Serializable {

    
//     private Integer feedsId;
    @XmlElement(name="userName")
     private String userName;
    @XmlElement(name="userImage")
     private String userImage;
    @XmlElement(name="feed")
     private String feed;
    @XmlElement(name="image")
     private String image;
    @XmlElement(name="feedTime")
     private Date feedTime;
    @XmlElement(name="likeFeed")
     private int likeFeed;

    public FeedsDto() {
    }

    public FeedsDto(String userName, String feed, String image, Date feedTime, int likeFeed) {
       this.userName = userName;
       this.feed = feed;
       this.image = image;
       this.feedTime = feedTime;
       this.likeFeed = likeFeed;
    }
   
    public String getUserName() {
        return userName;
    }

//    public Integer getFeedsId() {
//        return this.feedsId;
//    }
//    
//    public void setFeedsId(Integer feedsId) {
//        this.feedsId = feedsId;
//    }
    public void setUserName(String userName) {    
        this.userName = userName;
    }

    public String getFeed() {
        return this.feed;
    }
    
    public void setFeed(String feed) {
        this.feed = feed;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Date getFeedTime() {
        return this.feedTime;
    }
    
    public void setFeedTime(Date feedTime) {
        this.feedTime = feedTime;
    }
    public int getLikeFeed() {
        return this.likeFeed;
    }
    
    public void setLikeFeed(int likeFeed) {
        this.likeFeed = likeFeed;
    }

    public String getUserImage() {
        return userImage;
    }

    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }
    

@Override
    public String toString() {
        try {
            
            return new JSONObject()
                    .put("userName", userName)
                    .put("userImage", userImage)
                    .put("feed", feed)
                    .put("image", image)
                    .put("feedTime", feedTime)
                    .put("likeFeed", likeFeed).toString();
        } catch (Exception e) {
            return null;
        }


}
}


