package model.pojos;
// Generated 31-May-2016 22:35:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ElmoezMonuments generated by hbm2java
 */
public class ElmoezMonuments  implements java.io.Serializable {


     private Integer id;
     private String monumentsName;
     private String monumentsImage;
     private String description;
     private Set monumentsInformations = new HashSet(0);

    public ElmoezMonuments() {
    }

	
    public ElmoezMonuments(String monumentsName, String monumentsImage, String description) {
        this.monumentsName = monumentsName;
        this.monumentsImage = monumentsImage;
        this.description = description;
    }
    public ElmoezMonuments(String monumentsName, String monumentsImage, String description, Set monumentsInformations) {
       this.monumentsName = monumentsName;
       this.monumentsImage = monumentsImage;
       this.description = description;
       this.monumentsInformations = monumentsInformations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMonumentsName() {
        return this.monumentsName;
    }
    
    public void setMonumentsName(String monumentsName) {
        this.monumentsName = monumentsName;
    }
    public String getMonumentsImage() {
        return this.monumentsImage;
    }
    
    public void setMonumentsImage(String monumentsImage) {
        this.monumentsImage = monumentsImage;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMonumentsInformations() {
        return this.monumentsInformations;
    }
    
    public void setMonumentsInformations(Set monumentsInformations) {
        this.monumentsInformations = monumentsInformations;
    }




}


