package model.pojos;
// Generated 31-May-2016 22:35:14 by Hibernate Tools 4.3.1



/**
 * MonumentsInformation generated by hbm2java
 */
public class MonumentsInformation  implements java.io.Serializable {


     private MonumentsInformationId id;
     private ElmoezMonuments elmoezMonuments;
     private String pieceInformation;

    public MonumentsInformation() {
    }

    public MonumentsInformation(MonumentsInformationId id, ElmoezMonuments elmoezMonuments, String pieceInformation) {
       this.id = id;
       this.elmoezMonuments = elmoezMonuments;
       this.pieceInformation = pieceInformation;
    }
   
    public MonumentsInformationId getId() {
        return this.id;
    }
    
    public void setId(MonumentsInformationId id) {
        this.id = id;
    }
    public ElmoezMonuments getElmoezMonuments() {
        return this.elmoezMonuments;
    }
    
    public void setElmoezMonuments(ElmoezMonuments elmoezMonuments) {
        this.elmoezMonuments = elmoezMonuments;
    }
    public String getPieceInformation() {
        return this.pieceInformation;
    }
    
    public void setPieceInformation(String pieceInformation) {
        this.pieceInformation = pieceInformation;
    }




}


